workflows:
  my-workflow:
    scripts:
      - name: Build Android APK
        working_directory: android
        script: ./gradle assembleRelease
    artifacts:
      - app/build/outputs/**/**/*.apk
